export const sagaTypes = {
  FETCH_ALL_PRODUCTS_SAGA: "FETCH_ALL_PRODUCTS_SAGA",
  FETCH_MY_PRODUCTS_SAGA: "FETCH_MY_PRODUCTS_SAGA",
  FETCH_SINGLE_PRODUCT: "FETCH_SINGLE_PRODUCT",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  CREATE_PRODUCT: "CREATE_PRODUCT",
  GET_ORIGINS: "GET_ORIGINS",
};
